format_version = "1.0"

texts = {
    -- Instrument Properties
    ["propertyname Model"] = "Instrument Model",
    ["model Imperial Rosewood 5.0"] = "Imperial Rosewood 5.0",
    ["model Mayan Padauk 4.3"] = "Mayan Padauk 4.3",
    ["model Balafon Ancestral"] = "Balafon Ancestral",
    ["model Kalimba Artisan"] = "Kalimba Artisan 17-Key",

    ["propertyname Mallet Type"] = "Striker / Mallet Type",
    ["mallet Soft Yarn"] = "Soft Yarn / Thumb Flesh",
    ["mallet Medium Cord"] = "Medium Cord / Natural Thumb",
    ["mallet Hard Rubber"] = "Hard Rubber / Thumb Nail",
    ["mallet Wood Baton"] = "Wood Baton / Thumb Pick",

    ["propertyname Mallet Hardness"] = "Mallet Hardness",
    ["propertyname Strike Position"] = "Strike Position",
    ["propertyname Strike Variance"] = "Strike Variance",
    ["percent template"] = "^0 %",
    ["propertyname Resonator Tune"] = "Resonator Tune",
    ["cents template"] = "^0 Cents",
    ["propertyname Resonator Coupling"] = "Resonator Coupling",
    ["propertyname Bar Decay Scale"] = "Bar Decay Scale",
    ["multiplier template"] = "x^0",
    ["propertyname Mirliton Buzz"] = "Mirliton Buzz",
    ["propertyname Acoustic Artifacts"] = "Acoustic Artifacts",

    -- Premium Phenomena
    ["propertyname Sympathetic Halo"] = "Sympathetic Halo",
    ["propertyname Attack Pitch Glide"] = "Attack Pitch Glide",
    ["propertyname Frame Body Bloom"] = "Frame Body Bloom",

    -- Mic Mixer
    ["propertyname Close Mic"] = "Close Mic Level",
    ["propertyname Far Room Mic"] = "Far Room Mic Level",
    ["propertyname Piezo Pickup"] = "Piezo Pickup Level",
    ["propertyname Stereo Width"] = "Stereo Width",

    -- Preamp & Compressor
    ["propertyname Preamp Drive"] = "Preamp Drive",
    ["propertyname Warmth Tone"] = "Warmth Tone",
    ["propertyname Comp Amount"] = "Compressor Amount",
    ["propertyname Comp Attack"] = "Compressor Attack",
    ["propertyname Comp Release"] = "Compressor Release",
    ["ms template"] = "^0 ms",

    -- Master
    ["propertyname Master Volume"] = "Master Volume",
    ["propertyname Oversampling"] = "Oversampling",
    ["oversampling 2x (Studio Standard)"] = "2x (Studio Standard)",
    ["oversampling 4x (High Resolution)"] = "4x (High Resolution)",
    ["oversampling 8x (Pristine Archival)"] = "8x (Pristine Archival)",
    ["propertyname Velocity Curve"] = "Velocity Curve",
    ["velcurve Soft"] = "Soft",
    ["velcurve Linear"] = "Linear",
    ["velcurve Hard"] = "Hard",
    ["velcurve Expressive"] = "Expressive",
    ["propertyname Polyphony"] = "Polyphony",
    ["poly 8 Voices"] = "8 Voices",
    ["poly 16 Voices"] = "16 Voices",
    ["poly 24 Voices"] = "24 Voices",
    ["propertyname Master Tune"] = "Master Tune",
    ["propertyname Detune"] = "Key Detune Drift",
    ["detune cents template"] = "+/-^0 Cents",
    ["propertyname NoteOn Lamp"] = "Note-On Lamp",

    -- Automation / Remote Parameter Groups
    ["group instrument"] = "Instrument & Mallet",
    ["group bar"] = "Bar & Resonator",
    ["group mics"] = "Microphones",
    ["group dynamics"] = "Preamp & Compressor",
    ["group master"] = "Master & Engine",

    -- Remote Control UI Names
    ["rem_model"] = "Model",
    ["rem_mod"] = "Mod",
    ["rem_mallet"] = "Mallet",
    ["rem_mlt"] = "Mlt",
    ["rem_malthrd"] = "Hardness",
    ["rem_hrd"] = "Hrd",
    ["rem_pos"] = "Position",
    ["rem_psi"] = "Pos",
    ["rem_variance"] = "Variance",
    ["rem_var"] = "Var",
    ["rem_restun"] = "Res Tune",
    ["rem_rtn"] = "RTun",
    ["rem_rescoup"] = "Res Cpl",
    ["rem_rcp"] = "RCpl",
    ["rem_decay"] = "Decay",
    ["rem_dcy"] = "Dcy",
    ["rem_buzz"] = "Buzz",
    ["rem_buz"] = "Buz",
    ["rem_art"] = "Artifact",
    ["rem_ati"] = "Art",
    ["rem_symp"] = "Sympath",
    ["rem_sym"] = "Sym",
    ["rem_glide"] = "Glide",
    ["rem_gld"] = "Gld",
    ["rem_body"] = "Body",
    ["rem_bdy"] = "Bdy",
    ["rem_close"] = "Close",
    ["rem_cls"] = "Cls",
    ["rem_far"] = "Far",
    ["rem_piezo"] = "Piezo",
    ["rem_pzo"] = "Pzo",
    ["rem_width"] = "Width",
    ["rem_wdt"] = "Wdt",
    ["rem_drive"] = "Drive",
    ["rem_drv"] = "Drv",
    ["rem_warm"] = "Warmth",
    ["rem_wrm"] = "Wrm",
    ["rem_comp"] = "Comp",
    ["rem_cmp"] = "Cmp",
    ["rem_vol"] = "Volume",
    ["rem_vlm"] = "Vol",
    ["rem_osamp"] = "Oversamp",
    ["rem_os"] = "OS",
    ["rem_detune"] = "Detune",
    ["rem_dtn"] = "Dtn",
    ["rem_attack"] = "Attack",
    ["rem_atk"] = "Atk",
    ["rem_release"] = "Release",
    ["rem_rel"] = "Rel",
    ["rem_velcurve"] = "VelCurve",
    ["rem_vel"] = "Vel",
    ["rem_poly"] = "Poly",
    ["rem_ply"] = "Ply",
    ["rem_mtune"] = "MasTune",
    ["rem_mtn"] = "MTun",

    -- CV Inputs
    ["cv_note"] = "Sequencer Note CV Input",
    ["cv_gate"] = "Sequencer Gate CV Input",
    ["cv_mallet"] = "Mallet Hardness CV Input",
    ["cv_position"] = "Strike Position CV Input",
    ["cv_coupling"] = "Resonator Coupling CV Input",
    ["cv_volume"] = "Master Volume CV Input",
    ["cv_sympathetic"] = "Sympathetic Halo CV Input",

    -- Audio Outputs (Master Mix & Raw Direct Tap Outs)
    ["out_left"] = "Master Output Left (Mono)",
    ["out_right"] = "Master Output Right",
    ["out_close_l"] = "Close Mic Left (Raw Direct)",
    ["out_close_r"] = "Close Mic Right (Raw Direct)",
    ["out_far_l"] = "Far Room Left (Raw Direct)",
    ["out_far_r"] = "Far Room Right (Raw Direct)",
    ["out_piezo"] = "Piezo Pickup (Raw Direct)",
}
