format_version = "1.0"

texts = {
    ["property volume"] = "Volume",
    ["property preset gain"] = "Preset Level",
    ["property bender dco"] = "Bender DCO Depth",
    ["property bender vcf"] = "Bender VCF Depth",
    ["property bender lfo"] = "Bender LFO Depth",
    ["property portamento"] = "Portamento",
    ["property key mode"] = "Key Mode",
    ["property reassign held keys"] = "Reassign Held Keys",
    ["property lfo rate"] = "LFO Rate",
    ["property lfo delay"] = "LFO Delay",
    ["property dco lfo"] = "DCO LFO Depth",
    ["property pwm"] = "PWM",
    ["property pwm mode"] = "PWM Source",
    ["property range"] = "DCO Range",
    ["property saw"] = "Saw",
    ["property pulse"] = "Pulse",
    ["property sub"] = "Sub Oscillator",
    ["property noise"] = "Noise",
    ["property high pass"] = "High Pass",
    ["property cutoff"] = "VCF Cutoff",
    ["property resonance"] = "VCF Resonance",
    ["property env polarity"] = "VCF Envelope Polarity",
    ["property vcf env"] = "VCF Envelope Depth",
    ["property vcf lfo"] = "VCF LFO Depth",
    ["property key follow"] = "VCF Keyboard Follow",
    ["property vca mode"] = "VCA Mode",
    ["property vca level"] = "VCA Level",
    ["property attack"] = "Envelope Attack",
    ["property decay"] = "Envelope Decay",
    ["property sustain"] = "Envelope Sustain",
    ["property release"] = "Envelope Release",
    ["property chorus"] = "Chorus",
    ["property transpose"] = "Transpose",
    ["property master tune"] = "Master Tune",
    ["property velocity"] = "Velocity Sensitivity",
    ["property calibration"] = "Unit Character",
    ["property aging"] = "Aging",
    ["property chorus noise"] = "Chorus Noise",
    ["property polyphony"] = "Polyphony",
    ["property quality"] = "Processing Quality",
    ["property vcf tanh"] = "VCF Tanh",
    ["property vcf fast early"] = "VCF Fast Early",
    ["property vcf solver"] = "VCF Solver",
    ["property note on"] = "Note On",

    ["value off"] = "Off",
    ["value on"] = "On",
    ["value quality 1x"] = "1x",
    ["value quality 2x"] = "2x",
    ["value quality 4x"] = "4x",
    ["value vcf tanh exact"] = "Exact",
    ["value vcf tanh fast"] = "Fast",
    ["value vcf tanh poly"] = "Poly",
    ["value vcf fast early hermite"] = "Hermite",
    ["value vcf fast early cubic"] = "Cubic",
    ["value vcf solver max"] = "Max",
    ["value vcf solver high"] = "High",
    ["value vcf solver normal"] = "Normal",
    ["value poly 1"] = "Poly 1",
    ["value poly 2"] = "Poly 2",
    ["value unison"] = "Unison",
    ["value lfo"] = "LFO",
    ["value manual"] = "Manual",
    ["value range 16"] = "16'",
    ["value range 8"] = "8'",
    ["value range 4"] = "4'",
    ["value hpf boost"] = "Boost",
    ["value hpf 1"] = "1",
    ["value hpf 2"] = "2",
    ["value hpf 3"] = "3",
    ["value positive"] = "Positive",
    ["value negative"] = "Negative",
    ["value envelope"] = "Envelope",
    ["value gate"] = "Gate",
    ["value chorus off"] = "Off",
    ["value chorus one"] = "I",
    ["value chorus two"] = "II",
    ["value chorus one two"] = "I+II",

    ["unit cents"] = "^0 ct",
    ["unit percent"] = "^0 %",
    ["unit milliseconds"] = "^0 ms",
    ["unit seconds"] = "^0 s",
    ["unit milliseconds per octave"] = "^0 ms/oct",
    ["unit seconds per octave"] = "^0 s/oct",
    ["unit hertz"] = "^0 Hz",
    ["unit kilohertz"] = "^0 kHz",

    ["group performance"] = "Performance",
    ["group oscillator"] = "LFO and DCO",
    ["group filter amp"] = "Filter and Amplifier",
    ["group envelope character"] = "Envelope and Chorus",
    ["group engine quality"] = "Engine Quality and Model",
    ["cv note"] = "Sequencer Note CV Input",
    ["cv gate"] = "Sequencer Gate CV Input",
    ["cv cutoff"] = "Filter Cutoff CV Input",
    ["cv resonance"] = "Filter Resonance CV Input",
    ["cv volume"] = "Master Volume CV Input",
    ["cv vca level"] = "Amplifier Level CV Input",
    ["cv sub"] = "Sub Oscillator Level CV Input",
    ["cv noise"] = "Noise Level CV Input",
    ["audio left"] = "Main Out Left",
    ["audio right"] = "Main Out Right",

    ["remote volume"] = "Volume", ["remote4 volume"] = "Vol",
    ["remote bender dco"] = "Bend DCO", ["remote4 bender dco"] = "BDCO",
    ["remote bender vcf"] = "Bend VCF", ["remote4 bender vcf"] = "BVCF",
    ["remote bender lfo"] = "Bend LFO", ["remote4 bender lfo"] = "BLFO",
    ["remote portamento"] = "Porta", ["remote4 portamento"] = "Port",
    ["remote key mode"] = "Key Mode", ["remote4 key mode"] = "Mode",
    ["remote lfo rate"] = "LFO Rate", ["remote4 lfo rate"] = "Rate",
    ["remote lfo delay"] = "LFO Dly", ["remote4 lfo delay"] = "Dly",
    ["remote dco lfo"] = "DCO LFO", ["remote4 dco lfo"] = "DLFO",
    ["remote pwm"] = "PWM", ["remote4 pwm"] = "PWM",
    ["remote pwm mode"] = "PWM Src", ["remote4 pwm mode"] = "PSrc",
    ["remote range"] = "Range", ["remote4 range"] = "Rng",
    ["remote saw"] = "Saw", ["remote4 saw"] = "Saw",
    ["remote pulse"] = "Pulse", ["remote4 pulse"] = "Pls",
    ["remote sub"] = "Sub", ["remote4 sub"] = "Sub",
    ["remote noise"] = "Noise", ["remote4 noise"] = "Nse",
    ["remote high pass"] = "HPF", ["remote4 high pass"] = "HPF",
    ["remote cutoff"] = "Cutoff", ["remote4 cutoff"] = "Cut",
    ["remote resonance"] = "Res", ["remote4 resonance"] = "Res",
    ["remote env polarity"] = "Env Pol", ["remote4 env polarity"] = "Pol",
    ["remote vcf env"] = "VCF Env", ["remote4 vcf env"] = "Env",
    ["remote vcf lfo"] = "VCF LFO", ["remote4 vcf lfo"] = "FLFO",
    ["remote key follow"] = "VCF Key", ["remote4 key follow"] = "Key",
    ["remote vca mode"] = "VCA Mode", ["remote4 vca mode"] = "VMod",
    ["remote vca level"] = "VCA Lvl", ["remote4 vca level"] = "VLvl",
    ["remote attack"] = "Attack", ["remote4 attack"] = "A",
    ["remote decay"] = "Decay", ["remote4 decay"] = "D",
    ["remote sustain"] = "Sustain", ["remote4 sustain"] = "S",
    ["remote release"] = "Release", ["remote4 release"] = "R",
    ["remote chorus"] = "Chorus", ["remote4 chorus"] = "Chor",
    ["remote transpose"] = "Transp", ["remote4 transpose"] = "Trns",
    ["remote master tune"] = "M Tune", ["remote4 master tune"] = "Tune",
    ["remote velocity"] = "Velocity", ["remote4 velocity"] = "Vel",
    ["remote calibration"] = "Char", ["remote4 calibration"] = "Char",
    ["remote aging"] = "Aging", ["remote4 aging"] = "Age",
    ["remote chorus noise"] = "Ch Noise", ["remote4 chorus noise"] = "ChNs",
    ["remote polyphony"] = "Poly", ["remote4 polyphony"] = "Poly",
    ["remote quality"] = "Quality", ["remote4 quality"] = "Qual",
    ["remote vcf tanh"] = "Tanh", ["remote4 vcf tanh"] = "Tanh",
    ["remote vcf fast early"] = "Early", ["remote4 vcf fast early"] = "Erly",
    ["remote vcf solver"] = "Solver", ["remote4 vcf solver"] = "Slvr",
    ["remote reassign held keys"] = "Reassign", ["remote4 reassign held keys"] = "RAsn",
}
